[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer-runs = 10_000
verbosity = 3
evm_version = "cancun"

gas_reports = ["AfCvx", "CleverCvxStrategy"]

[fmt]
bracket_spacing = true

[fuzz]
runs = 10

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"